# Generated by Django 3.1.7 on 2021-05-06 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=45, null=True)),
                ('vorname', models.CharField(max_length=45, null=True)),
                ('nachname', models.CharField(max_length=45, null=True)),
                ('mitarbeiternummer', models.CharField(max_length=45, null=True)),
                ('email', models.CharField(max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pruefung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=45)),
                ('passwort', models.CharField(max_length=45, null=True)),
                ('modul', models.CharField(max_length=45, null=True)),
                ('semester', models.CharField(max_length=45, null=True)),
                ('pruefer', models.CharField(max_length=45, null=True)),
                ('raumnummer', models.CharField(max_length=45, null=True)),
                ('dauer', models.FloatField(max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vorname', models.CharField(max_length=45, null=True)),
                ('nachname', models.CharField(max_length=45, null=True)),
                ('mitarbeiternummer', models.CharField(max_length=45, null=True)),
                ('studiengang', models.CharField(max_length=45, null=True)),
                ('email', models.CharField(max_length=45, null=True)),
            ],
        ),
    ]
