# Generated by Django 3.2 on 2021-04-22 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hftcheckin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='nachnamen',
            new_name='nachname',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='vornamen',
            new_name='vorname',
        ),
    ]
