# Generated by Django 3.2 on 2021-04-24 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hftcheckin', '0003_professor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pruefung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=45)),
                ('passwort', models.CharField(max_length=45, null=True)),
                ('modul', models.CharField(max_length=45, null=True)),
                ('semester', models.CharField(max_length=45, null=True)),
                ('pruefer', models.CharField(max_length=45, null=True)),
                ('raumnummer', models.CharField(max_length=45, null=True)),
                ('dauer', models.FloatField(max_length=45, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='professor',
            name='email',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='professor',
            name='mitarbeiternummer',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='professor',
            name='passwort',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='mitarbeiternummer',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='passwort',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='studiengang',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='professor',
            name='nachname',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='professor',
            name='titel',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='professor',
            name='vorname',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='nachname',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='vorname',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
