# Generated by Django 3.2 on 2021-05-03 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hftcheckin', '0005_auto_20210424_1117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='mitarbeiternummer',
            new_name='matrikelnummer',
        ),
    ]
