# Generated by Django 3.2.3 on 2021-05-26 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hftcheckin', '0011_professor_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='pruefung',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hftcheckin.student'),
        ),
    ]
