# Generated by Django 3.2.3 on 2021-05-26 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hftcheckin', '0012_pruefung_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='pruefung',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hftcheckin.pruefung'),
        ),
    ]
