# Generated by Django 3.2.3 on 2021-05-26 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hftcheckin', '0014_auto_20210526_2115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pruefung',
            name='student',
        ),
        migrations.AddField(
            model_name='pruefung',
            name='student',
            field=models.ManyToManyField(to='hftcheckin.Student'),
        ),
    ]
