# Generated by Django 3.2.3 on 2021-06-05 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hftcheckin', '0018_studentschreibtpruefung'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentSchreibtPruefung',
        ),
    ]
