# Generated by Django 3.2.3 on 2021-06-05 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hftcheckin', '0020_student_teilnahme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='teilnahme',
        ),
    ]
